name: Publish Core Package to NPM

on:
  push:
    branches: [master]
    paths:
      - 'packages/core/**'
      - '.github/workflows/npm-publish.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # 需要ID token进行npm认证

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm #

      - name: Install dependencies
        run: pnpm install

      - name: Build
        working-directory: ./packages/core
        run: pnpm run build

      - name: Publish
        working-directory: ./packages/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
          npm config set registry=https://registry.npmjs.org/
          npm publish --access public
