name: Release Electron App

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Build Electron App
        run: pnpm -F interface-web run build
        env:
          NODE_ENV: production

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./packages/interface-electron/dist_electron/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
