name: Tag Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      # - uses: oven-sh/setup-bun@v1 # 如果使用 Bun，请取消注释
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm # 或 pnpm / yarn
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: pnpm install # 或 pnpm install / yarn install / bun install

      - name: Get Commit Message
        id: commit
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Get Version from package.json
        id: version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Determine Tag Type
        id: tag
        run: |
          message="${{ env.message }}"
          if echo "$message" | grep -iqE '^feat'; then
            echo "tag=v${{ env.version }}" >> $GITHUB_ENV
          elif echo "$message" | grep -iqE '^fix'; then
            echo "tag=v${{ env.version }}-patch" >> $GITHUB_ENV
          else
            echo "No tag created"
          fi

      - name: Create Tag
        if: env.tag != ''
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.tag }}
          git push origin ${{ env.tag }}
